import React, { useMemo, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { ManagerShell, managerStyles } from '../../components/manager/ManagerShell';
import { FilterButton, StatusPill } from '../../components/manager/ManagerUI';
import { alerts as initialAlerts } from '../../components/manager/data';

export default function AlertsResponse() {
  const [filter, setFilter] = useState('All alerts');
  const [items, setItems] = useState(initialAlerts);
  const filtered = useMemo(() => filter === 'All alerts' ? items : items.filter((item) => item.status === filter || item.severity === filter), [filter, items]);
  const resolve = (id: string) => setItems((current) => current.map((item) => item.id === id ? { ...item, status: 'Resolved' } : item));
  return <ManagerShell active="alerts"><Text style={managerStyles.pageTitle}>Alerts & response</Text><Text style={managerStyles.pageSubtitle}>Review and coordinate responses to events across the park.</Text><View style={styles.filters}><FilterButton label="All alerts" selected={filter === 'All alerts'} onPress={() => setFilter('All alerts')} /><FilterButton label="Active" selected={filter === 'Active'} onPress={() => setFilter('Active')} /><FilterButton label="High priority" selected={filter === 'High'} onPress={() => setFilter('High')} /><FilterButton label="Resolved" selected={filter === 'Resolved'} onPress={() => setFilter('Resolved')} /></View><View style={managerStyles.card}><View style={styles.tableHead}><Text style={[styles.head, { flex: 2 }]}>Alert</Text><Text style={styles.head}>Location</Text><Text style={styles.head}>Severity</Text><Text style={styles.head}>Status</Text><Text style={styles.head}>Action</Text></View>{filtered.map((item) => <View style={styles.row} key={item.id}><View style={{ flex: 2 }}><Text style={styles.title}>{item.title}</Text><Text style={managerStyles.cardMuted}>{item.id} · {item.time}</Text></View><Text style={styles.cell}>{item.zone}</Text><View style={{ flex: 1 }}><StatusPill value={item.severity} /></View><View style={{ flex: 1 }}><StatusPill value={item.status} /></View><Pressable style={styles.action} onPress={() => item.status === 'Resolved' ? Alert.alert(item.id, 'This alert has already been resolved.') : resolve(item.id)}><Ionicons name={item.status === 'Resolved' ? 'eye-outline' : 'checkmark-circle-outline'} size={18} color="#2B8263" /><Text style={styles.actionText}>{item.status === 'Resolved' ? 'View' : 'Resolve'}</Text></Pressable></View>)}</View></ManagerShell>;
}
const styles = StyleSheet.create({ filters: { flexDirection: 'row', gap: 8, marginBottom: 18, flexWrap: 'wrap' }, tableHead: { flexDirection: 'row', gap: 12, borderBottomWidth: 1, borderBottomColor: '#E8EFEB', paddingBottom: 11 }, head: { flex: 1, color: '#8A9992', fontSize: 10, fontWeight: '800', textTransform: 'uppercase' }, row: { flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomWidth: 1, borderBottomColor: '#EFF3F0', paddingVertical: 15 }, title: { color: '#234138', fontSize: 12, fontWeight: '700', marginBottom: 3 }, cell: { flex: 1, color: '#53655D', fontSize: 12 }, action: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 5 }, actionText: { color: '#2B8263', fontSize: 11, fontWeight: '700' } });
