import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { ManagerShell, managerStyles } from '../../components/manager/ManagerShell';
import { FilterButton, StatusPill } from '../../components/manager/ManagerUI';

const cameras = ['North Ridge · Camera 04', 'River Gate · Camera 02', 'East Boundary · Camera 08', 'South Camp · Camera 01'];
export default function LiveMonitoring() {
  const [selected, setSelected] = useState(0);
  const [live, setLive] = useState(true);
  return <ManagerShell active="monitoring"><View style={styles.titleRow}><View><Text style={managerStyles.pageTitle}>Live monitoring</Text><Text style={managerStyles.pageSubtitle}>Monitor cameras, ranger locations, and activity in real time.</Text></View><View style={styles.live}><View style={styles.liveDot} /><Text style={styles.liveText}>{live ? 'LIVE' : 'PAUSED'}</Text><Pressable onPress={() => setLive(!live)}><Ionicons name={live ? 'pause' : 'play'} size={15} color="#2B8263" /></Pressable></View></View>
    <View style={styles.filters}><FilterButton label="All zones" selected /><FilterButton label="Camera status" /><FilterButton label="Last 24 hours" /></View>
    <View style={styles.cameraGrid}>{cameras.map((camera, index) => <Pressable key={camera} onPress={() => setSelected(index)} style={[managerStyles.card, styles.camera, selected === index && styles.cameraSelected]}><View style={styles.cameraImage}><View style={styles.scanLine} /><Ionicons name="videocam" size={27} color="#B6D3C5" /><Text style={styles.imageText}>LIVE FEED</Text><View style={styles.timestamp}><Text style={styles.timestampText}>{live ? '00:12:48' : 'PAUSED'}</Text></View></View><View style={styles.cameraFooter}><View><Text style={styles.cameraName}>{camera}</Text><Text style={managerStyles.cardMuted}>Motion detected · 2 min ago</Text></View><StatusPill value="Online" /></View></Pressable>)}</View>
    <View style={[managerStyles.card, styles.mapCard]}><View style={managerStyles.sectionRow}><View><Text style={managerStyles.cardTitle}>Ranger locations</Text><Text style={managerStyles.cardMuted}>Live positions across the park</Text></View><StatusPill value="24 active" /></View><View style={styles.map}><View style={styles.mapRoadOne} /><View style={styles.mapRoadTwo} /><View style={[styles.marker, { left: '28%', top: '35%' }]}><Ionicons name="location" size={28} color="#D35F50" /></View><View style={[styles.marker, { left: '63%', top: '60%' }]}><Ionicons name="location" size={28} color="#2B8263" /></View><View style={[styles.marker, { left: '78%', top: '24%' }]}><Ionicons name="location" size={28} color="#2B8263" /></View><Text style={styles.mapLabel}>NORTH RIDGE</Text><Text style={[styles.mapLabel, { right: '12%', bottom: '19%' }]}>RIVER GATE</Text></View></View>
  </ManagerShell>;
}
const styles = StyleSheet.create({ titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, live: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, height: 34, backgroundColor: '#E6F3ED', borderRadius: 18 }, liveDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#D35F50' }, liveText: { color: '#2B8263', fontSize: 10, fontWeight: '800' }, filters: { flexDirection: 'row', gap: 8, marginBottom: 18, flexWrap: 'wrap' }, cameraGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 16, marginBottom: 18 }, camera: { flex: 1, minWidth: 260, padding: 10, margin: 0 }, cameraSelected: { borderColor: '#2B8263', borderWidth: 2 }, cameraImage: { height: 150, borderRadius: 9, backgroundColor: '#29443A', alignItems: 'center', justifyContent: 'center', position: 'relative', overflow: 'hidden' }, scanLine: { position: 'absolute', left: 0, right: 0, top: '45%', borderTopWidth: 1, borderTopColor: '#77BCA0', opacity: .35 }, imageText: { color: '#B6D3C5', fontSize: 9, letterSpacing: 1.5, marginTop: 7 }, timestamp: { position: 'absolute', right: 8, top: 8, backgroundColor: '#17342B', paddingHorizontal: 6, paddingVertical: 3, borderRadius: 4 }, timestampText: { fontSize: 9, color: '#FFFFFF' }, cameraFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 11 }, cameraName: { color: '#234138', fontSize: 12, fontWeight: '700', marginBottom: 3 }, mapCard: { marginBottom: 20 }, map: { height: 230, borderRadius: 10, backgroundColor: '#DDEBE2', overflow: 'hidden', position: 'relative' }, mapRoadOne: { position: 'absolute', height: 25, width: '130%', backgroundColor: '#C9DED0', transform: [{ rotate: '-22deg' }], top: '45%', left: '-10%' }, mapRoadTwo: { position: 'absolute', height: 14, width: '110%', backgroundColor: '#C9DED0', transform: [{ rotate: '35deg' }], top: '24%', left: '5%' }, marker: { position: 'absolute' }, mapLabel: { position: 'absolute', left: '12%', top: '18%', color: '#719183', fontSize: 10, fontWeight: '800', letterSpacing: 1 } });
