import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { ManagerShell, managerStyles } from '../../components/manager/ManagerShell';
import { StatCard, StatusPill } from '../../components/manager/ManagerUI';
import { alerts, patrols } from '../../components/manager/data';
import { router } from 'expo-router';

export default function ManagerOverview() {
  return <ManagerShell active="overview"><Text style={managerStyles.pageTitle}>Park overview</Text><Text style={managerStyles.pageSubtitle}>Tuesday, October 8, 2024 · Serengeti National Park</Text>
    <Pressable style={managerStyles.card} onPress={() => router.push('/community-operations')}><Text style={managerStyles.cardTitle}>Community Reports &amp; Response</Text><Text style={managerStyles.cardMuted}>Sightings, crop raiding and boundary conflict patterns</Text></Pressable>
    <View style={styles.stats}><StatCard icon="people-outline" label="Rangers on duty" value="24 / 32" change="+8.2%" /><StatCard icon="notifications-outline" label="Active alerts" value="03" change="-12.5%" tone="#D35F50" /><StatCard icon="walk-outline" label="Patrol coverage" value="78%" change="+5.4%" tone="#4D84A8" /><StatCard icon="shield-checkmark-outline" label="Incidents this month" value="18" change="-6.1%" tone="#C98A2E" /></View>
    <View style={styles.grid}><View style={[managerStyles.card, styles.wide]}><View style={managerStyles.sectionRow}><View><Text style={managerStyles.cardTitle}>Park activity</Text><Text style={managerStyles.cardMuted}>Patrol coverage and alerts over the last 7 days</Text></View><Pressable style={styles.week}><Text style={styles.weekText}>This week</Text><Ionicons name="chevron-down" size={13} color="#71817A" /></Pressable></View><View style={styles.chart}><View style={styles.yAxis}><Text>100%</Text><Text>75%</Text><Text>50%</Text><Text>25%</Text><Text>0%</Text></View><View style={styles.chartBody}><View style={styles.gridLines}>{[0, 1, 2, 3].map((i) => <View key={i} style={styles.gridLine} />)}</View><View style={styles.bars}>{[58, 73, 54, 80, 68, 87, 76].map((height, i) => <View key={i} style={styles.barGroup}><View style={[styles.bar, { height: `${height}%` }]} /><View style={[styles.alertBar, { height: `${Math.max(12, height - 45)}%` }]} /><Text style={styles.day}>{['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'][i]}</Text></View>)}</View></View></View></View></View>
    <View style={styles.grid}><View style={[managerStyles.card, styles.half]}><View style={managerStyles.sectionRow}><Text style={managerStyles.cardTitle}>Priority alerts</Text><Pressable onPress={() => router.push('/(manager)/alerts' as never)}><Text style={managerStyles.link}>View all</Text></Pressable></View>{alerts.slice(0, 3).map((alert) => <Pressable style={styles.listRow} key={alert.id} onPress={() => router.push({ pathname: '/(manager)/alerts', params: { alertId: alert.firestoreId } } as never)} accessibilityRole="button" accessibilityLabel={`View details for ${alert.title}`}><View style={styles.alertIcon}><Ionicons name="warning-outline" size={16} color="#D35F50" /></View><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{alert.title}</Text><Text style={managerStyles.cardMuted}>{alert.zone} · {alert.time}</Text></View><StatusPill value={alert.severity} /><Ionicons name="chevron-forward" size={16} color="#8A9992" /></Pressable>)}</View><View style={[managerStyles.card, styles.half]}><View style={managerStyles.sectionRow}><Text style={managerStyles.cardTitle}>Patrol teams</Text><Pressable onPress={() => router.push('/(manager)/patrols' as never)}><Text style={managerStyles.link}>Manage</Text></Pressable></View>{patrols.slice(0, 3).map((patrol) => <View style={styles.listRow} key={patrol.name}><View style={styles.teamAvatar}><Text style={styles.teamInitial}>{patrol.name[0]}</Text></View><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{patrol.name}</Text><Text style={managerStyles.cardMuted}>{patrol.ranger} · {patrol.zone}</Text></View><StatusPill value={patrol.status} /></View>)}</View></View>
  </ManagerShell>;
}
const styles = StyleSheet.create({ stats: { flexDirection: 'row', flexWrap: 'wrap', gap: 14, marginBottom: 18 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 18, marginBottom: 18 }, wide: { flex: 1, minWidth: 480 }, half: { flex: 1, minWidth: 320 }, week: { borderWidth: 1, borderColor: '#DCE7E1', borderRadius: 7, height: 32, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', gap: 8 }, weekText: { fontSize: 11, color: '#53655D' }, chart: { height: 190, flexDirection: 'row', marginTop: 12 }, yAxis: { justifyContent: 'space-between', paddingBottom: 22, width: 35 }, yAxisText: { fontSize: 9, color: '#9BA8A2' }, chartBody: { flex: 1, position: 'relative' }, gridLines: { ...StyleSheet.absoluteFill, justifyContent: 'space-around', paddingBottom: 22 }, gridLine: { borderTopWidth: 1, borderColor: '#EDF2EF' }, bars: { height: '100%', flexDirection: 'row', justifyContent: 'space-around', alignItems: 'flex-end', paddingHorizontal: 12 }, barGroup: { flex: 1, height: '100%', alignItems: 'center', justifyContent: 'flex-end', flexDirection: 'row', gap: 2 }, bar: { width: 12, maxHeight: '80%', backgroundColor: '#76B9A0', borderRadius: 4 }, alertBar: { width: 12, maxHeight: '45%', backgroundColor: '#E8B7A9', borderRadius: 4 }, day: { position: 'absolute', bottom: 0, fontSize: 9, color: '#9BA8A2' }, listRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 11, borderBottomWidth: 1, borderBottomColor: '#EFF3F0' }, alertIcon: { width: 30, height: 30, borderRadius: 8, backgroundColor: '#FCEDEA', alignItems: 'center', justifyContent: 'center' }, rowTitle: { color: '#234138', fontSize: 12, fontWeight: '700', marginBottom: 3 }, teamAvatar: { width: 30, height: 30, borderRadius: 15, backgroundColor: '#DDECE5', alignItems: 'center', justifyContent: 'center' }, teamInitial: { color: '#2B8263', fontWeight: '800' } });
