import React, { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { ManagerShell, managerStyles } from '../../components/manager/ManagerShell';
import { FilterButton, StatusPill } from '../../components/manager/ManagerUI';
import { patrols as patrolData } from '../../components/manager/data';

export default function Patrols() {
  const [filter, setFilter] = useState('All teams');
  const [teams, setTeams] = useState(patrolData);
  const filtered = filter === 'All teams' ? teams : teams.filter((team) => team.status === filter);
  return <ManagerShell active="patrols"><View style={styles.titleRow}><View><Text style={managerStyles.pageTitle}>Patrols</Text><Text style={managerStyles.pageSubtitle}>Track teams, coverage, and daily patrol performance.</Text></View><Pressable style={styles.primary} onPress={() => Alert.alert('New patrol', 'Patrol scheduling will be connected to the ranger roster.') }><Ionicons name="add" size={17} color="#FFF" /><Text style={styles.primaryText}>Schedule patrol</Text></Pressable></View><View style={styles.filters}><FilterButton label="All teams" selected={filter === 'All teams'} onPress={() => setFilter('All teams')} /><FilterButton label="On patrol" selected={filter === 'On patrol'} onPress={() => setFilter('On patrol')} /><FilterButton label="Break" selected={filter === 'Break'} onPress={() => setFilter('Break')} /><FilterButton label="Completed" selected={filter === 'Completed'} onPress={() => setFilter('Completed')} /></View><View style={styles.stats}><View style={[managerStyles.card, styles.small]}><Text style={managerStyles.cardMuted}>Teams active now</Text><Text style={styles.big}>02</Text><StatusPill value="Live" /></View><View style={[managerStyles.card, styles.small]}><Text style={managerStyles.cardMuted}>Coverage today</Text><Text style={styles.big}>78%</Text><Text style={styles.good}>+5.4% vs yesterday</Text></View><View style={[managerStyles.card, styles.small]}><Text style={managerStyles.cardMuted}>Distance covered</Text><Text style={styles.big}>146.8 km</Text><Text style={styles.good}>Across 12 zones</Text></View></View><View style={styles.teamGrid}>{filtered.map((team) => <View key={team.name} style={[managerStyles.card, styles.team]}><View style={styles.teamTop}><View style={styles.teamIcon}><Ionicons name="people-outline" size={21} color="#2B8263" /></View><StatusPill value={team.status} /></View><Text style={styles.teamName}>{team.name}</Text><Text style={managerStyles.cardMuted}>{team.ranger}</Text><View style={styles.zone}><Ionicons name="location-outline" size={14} color="#71817A" /><Text style={managerStyles.cardMuted}>{team.zone}</Text></View><View style={styles.progressLabel}><Text style={managerStyles.cardMuted}>Patrol progress</Text><Text style={styles.percent}>{team.progress}%</Text></View><View style={styles.progress}><View style={[styles.progressFill, { width: `${team.progress}%` }]} /></View><Text style={styles.last}>{team.last}</Text><Pressable style={styles.details} onPress={() => Alert.alert(team.name, `${team.ranger} is assigned to ${team.zone}.`)}><Text style={managerStyles.link}>View team details</Text><Ionicons name="arrow-forward" size={14} color="#2B8263" /></Pressable></View>)}</View></ManagerShell>;
}
const styles = StyleSheet.create({ titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, primary: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#2B8263', borderRadius: 8, paddingHorizontal: 13, height: 38 }, primaryText: { color: '#FFF', fontSize: 12, fontWeight: '700' }, filters: { flexDirection: 'row', gap: 8, marginBottom: 18, flexWrap: 'wrap' }, stats: { flexDirection: 'row', flexWrap: 'wrap', gap: 14, marginBottom: 18 }, small: { flex: 1, minWidth: 160, margin: 0 }, big: { color: '#17342B', fontSize: 25, fontWeight: '800', marginVertical: 8 }, good: { color: '#2B8263', fontSize: 11 }, teamGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 15 }, team: { flex: 1, minWidth: 245, margin: 0 }, teamTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, teamIcon: { width: 40, height: 40, borderRadius: 11, backgroundColor: '#E5F2EC', alignItems: 'center', justifyContent: 'center' }, teamName: { color: '#234138', fontSize: 16, fontWeight: '800', marginTop: 15, marginBottom: 4 }, zone: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 13 }, progressLabel: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 20, marginBottom: 7 }, percent: { color: '#2B8263', fontWeight: '800', fontSize: 12 }, progress: { height: 7, borderRadius: 5, backgroundColor: '#E5EEE9', overflow: 'hidden' }, progressFill: { height: '100%', backgroundColor: '#2B8263', borderRadius: 5 }, last: { color: '#8A9992', fontSize: 11, marginTop: 9 }, details: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderTopWidth: 1, borderTopColor: '#EDF2EF', paddingTop: 13, marginTop: 14 } });
