import React, { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { ManagerShell, managerStyles } from '../../components/manager/ManagerShell';
import { FilterButton, StatCard } from '../../components/manager/ManagerUI';

export default function Reports() {
  const [period, setPeriod] = useState('This month');
  const exportReport = () => Alert.alert('Report ready', `Park activity report for ${period} has been generated.`);
  return <ManagerShell active="reports"><View style={styles.titleRow}><View><Text style={managerStyles.pageTitle}>Reports & analytics</Text><Text style={managerStyles.pageSubtitle}>Understand trends and export operational reports.</Text></View><Pressable style={styles.primary} onPress={exportReport}><Ionicons name="download-outline" size={17} color="#FFF" /><Text style={styles.primaryText}>Export report</Text></Pressable></View><View style={styles.filters}><FilterButton label={period} selected onPress={() => setPeriod(period === 'This month' ? 'Last month' : 'This month')} /><FilterButton label="All zones" /><FilterButton label="PDF report" /></View><View style={styles.stats}><StatCard icon="walk-outline" label="Patrol hours" value="1,248" change="+12.8%" /><StatCard icon="shield-checkmark-outline" label="Response rate" value="94.6%" change="+3.2%" tone="#4D84A8" /><StatCard icon="people-outline" label="Community reports" value="86" change="+18.4%" tone="#C98A2E" /></View><View style={styles.grid}><View style={[managerStyles.card, styles.chartCard]}><View style={managerStyles.sectionRow}><View><Text style={managerStyles.cardTitle}>Incident trends</Text><Text style={managerStyles.cardMuted}>Reports by category</Text></View><Text style={managerStyles.link}>{period}</Text></View><View style={styles.trendChart}>{[{ label: 'Wildlife', value: 70, color: '#72B399' }, { label: 'Illegal activity', value: 44, color: '#D98270' }, { label: 'Community', value: 57, color: '#D2A25E' }, { label: 'Other', value: 26, color: '#A4B5AD' }].map((bar) => <View key={bar.label} style={styles.trendRow}><Text style={styles.trendLabel}>{bar.label}</Text><View style={styles.trendTrack}><View style={[styles.trendFill, { width: `${bar.value}%`, backgroundColor: bar.color }]} /></View><Text style={styles.trendValue}>{bar.value}</Text></View>)}</View></View><View style={[managerStyles.card, styles.chartCard]}><View style={managerStyles.sectionRow}><View><Text style={managerStyles.cardTitle}>Team performance</Text><Text style={managerStyles.cardMuted}>Coverage by patrol team</Text></View><Ionicons name="ellipsis-horizontal" size={19} color="#71817A" /></View>{['Alpha Team', 'Bravo Team', 'Charlie Team', 'Delta Team'].map((team, i) => <View key={team} style={styles.performance}><View style={styles.performanceLabel}><Text style={styles.trendLabel}>{team}</Text><Text style={styles.trendValue}>{[92, 84, 76, 68][i]}%</Text></View><View style={styles.trendTrack}><View style={[styles.trendFill, { width: `${[92, 84, 76, 68][i]}%`, backgroundColor: '#2B8263' }]} /></View></View>)}</View></View></ManagerShell>;
}
const styles = StyleSheet.create({ titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, primary: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#2B8263', borderRadius: 8, paddingHorizontal: 13, height: 38 }, primaryText: { color: '#FFF', fontSize: 12, fontWeight: '700' }, filters: { flexDirection: 'row', gap: 8, marginBottom: 18, flexWrap: 'wrap' }, stats: { flexDirection: 'row', flexWrap: 'wrap', gap: 14, marginBottom: 18 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 18 }, chartCard: { flex: 1, minWidth: 330, margin: 0 }, trendChart: { gap: 18, marginTop: 16 }, trendRow: { flexDirection: 'row', alignItems: 'center', gap: 10 }, trendLabel: { width: 84, color: '#53655D', fontSize: 11 }, trendTrack: { flex: 1, height: 9, backgroundColor: '#E8F0EC', borderRadius: 5, overflow: 'hidden' }, trendFill: { height: '100%', borderRadius: 5 }, trendValue: { width: 26, textAlign: 'right', color: '#234138', fontSize: 11, fontWeight: '800' }, performance: { marginTop: 17 }, performanceLabel: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 7 } });
